### ISSUE TITLE
convert the network object "trolls" to igraph

### ISSUE THREAD

**Issue by shangyuan232** [cmarcum/RussianTrollNetwork#1]
Hi, I want to output the network "trolls" with vetex attributes to a graphml format file. 
The way I tried is to convert the network object "trolls" to igraph first after setting vertex attributes, but it shows as follows.

> g <- asIgraph(trolls)
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1245, 9567, 1454

Do you have any suggestions?

**Comment by cmarcum** [comment]
Hi,

You can convert the network object to a sociomatrix using either the square
bracket operator trolls[,] or using as.sociomatrix(trolls) in the sna
package. Attributes can be extracted using the get.vertex.attribute()
function in the network package.

Best, Chris

**Comment by shangyuan232** [comment]
Hi  Chris,

Thanks for your advice! I got what I want after using as.sociomatrix(),graph.adjacency(), and set_vertex_attr() functions.

Cheers,
Yuanyuan

**Comment by cmarcum** [comment]
Great! Enjoy.
